# Sources for Cosmic Timeline
# Structured for APA 7th edition compliance

- id: S001
  type: journal
  author: Planck Collaboration
  year: 2018
  title: "Planck 2018 results. VI. Cosmological parameters"
  journal: Astronomy & Astrophysics
  volume: 641
  pages: A6
  doi: 10.1051/0004-6361/201833910
  url: https://arxiv.org/abs/1807.06209

- id: S002
  type: website
  author: NASA
  year: n.d.
  title: "Big Bang and the origin of the universe"
  publisher: NASA Science
  url: https://science.nasa.gov/universe/

- id: S003
  type: report
  author: International Commission on Stratigraphy
  year: 2024
  title: International Chronostratigraphic Chart
  publisher: International Commission on Stratigraphy
  url: https://stratigraphy.org/ICSchart/ChronostratChart2024-12.pdf

- id: S004
  type: website
  author: U.S. Geological Survey
  year: n.d.
  title: "Geologic time: Age of the Earth"
  publisher: USGS
  url: https://pubs.usgs.gov/gip/geotime/age.html

- id: S005
  type: journal
  author: "Schulte, P., Alegret, L., Arenillas, I., Arz, J. A., Barton, P. J., Bown, P. R., Bralower, T. J., Christeson, G. L., Claeys, P., Cockell, C. S., Collins, G. S., Deutsch, A., Goldin, T. J., Goto, K., Grajales-Nishimura, J. M., Grieve, R. A. F., Gulick, S. P. S., Johnson, K. R., Kiessling, W., ... Willumsen, P. S."
  year: 2010
  title: The Chicxulub asteroid impact and mass extinction at the Cretaceous-Paleogene boundary
  journal: Science
  volume: 327
  issue: 5970
  pages: 1214-1218
  doi: 10.1126/science.1177265
  url: https://www.science.org/doi/10.1126/science.1177265

- id: S006
  type: website
  author: Smithsonian National Museum of Natural History
  year: n.d.
  title: What does it mean to be human?
  publisher: Smithsonian Institution
  url: https://humanorigins.si.edu/

- id: S007
  type: website
  author: Smithsonian National Museum of Natural History
  year: n.d.
  title: Oldowan tools are 3 million years old
  publisher: Smithsonian Institution
  url: https://humanorigins.si.edu/research/whats-hot-human-origins/oldowan-tools-3-million-years-ago

- id: S008
  type: website
  author: NASA
  year: n.d.
  title: "Webb series: Finding the first galaxies"
  publisher: NASA
  url: https://www.nasa.gov/podcasts/curious-universe/webb-series-finding-the-first-galaxies/

- id: S009
  type: website
  author: United Nations
  year: n.d.
  title: Decolonization
  publisher: United Nations
  url: https://www.un.org/en/global-issues/decolonization

- id: S010
  type: encyclopedia
  author: Encyclopaedia Britannica
  year: n.d.
  title: Printing press
  publisher: Encyclopaedia Britannica
  url: https://www.britannica.com/technology/printing-press

- id: S011
  type: encyclopedia
  author: Encyclopaedia Britannica
  year: n.d.
  title: Johannes Gutenberg
  publisher: Encyclopaedia Britannica
  url: https://www.britannica.com/biography/Johannes-Gutenberg

- id: S012
  type: report
  author: Intergovernmental Panel on Climate Change
  year: 2023
  title: "Climate change 2023: Synthesis report"
  publisher: IPCC
  url: https://www.ipcc.ch/report/ar6/syr/downloads/report/IPCC_AR6_SYR_LongerReport.pdf

- id: S013
  type: website
  author: "Leiner, B. M., Cerf, V. G., Clark, D. D., Kahn, R. E., Kleinrock, L., Lynch, D. C., Postel, J., Roberts, L. G., & Wolff, S."
  year: 2009
  title: A brief history of the Internet
  publisher: Internet Society
  url: https://www.internetsociety.org/internet/history-internet/brief-history-internet/

- id: S014
  type: website
  author: Centers for Disease Control and Prevention
  year: n.d.
  title: Immunization and vaccination campaigns
  publisher: CDC Museum
  url: https://www.cdc.gov/museum/online/story-of-cdc/immunization/index.html

- id: S015
  type: journal
  author: "Gaynes, R."
  year: 2017
  title: "The discovery of penicillin: New insights after more than 75 years of clinical use"
  journal: Emerging Infectious Diseases
  volume: 23
  issue: 5
  pages: 849-853
  doi: 10.3201/eid2305.161556
  url: https://wwwnc.cdc.gov/eid/article/23/5/16-1556_article

- id: S016
  type: report
  author: Bell System Memorial
  year: n.d.
  title: The transistor
  publisher: Bell System Memorial
  url: https://memorial.bellsystem.com/pdf/trans-history.pdf

- id: S017
  type: website
  author: IEEE Engineering and Technology History Wiki
  year: n.d.
  title: "Invention of the first transistor at Bell Telephone Laboratories, Inc., 1947"
  publisher: IEEE
  url: https://ethw.org/Milestones%3AInvention_of_the_First_Transistor_at_Bell_Telephone_Laboratories%2C_Inc.%2C_1947
